### ISSUE TITLE
what env is used?

### ISSUE THREAD

**Issue by iTomxy** [johannakarras/DreamPose#13]
I got the following error when I run the demo provided in README:
```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/liangtianyou/codes/DreamPose/test.py", line 4, in <module>
    from pipelines.dual_encoder_pipeline import StableDiffusionImg2ImgPipeline
  File "/home/liangtianyou/codes/DreamPose/pipelines/dual_encoder_pipeline.py", line 31, in <module>
    from models.unet_dual_encoder import get_unet, Embedding_Adapter
  File "/home/liangtianyou/codes/DreamPose/models/unet_dual_encoder.py", line 16, in <module>
    from diffusers.models import BasicTransformerBlock
ImportError: cannot import name 'BasicTransformerBlock' from 'diffusers.models' (/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/__init__.py)
```
My env exported by `pip freeze`:
```
accelerate==0.18.0
antlr4-python3-runtime==4.9.3
certifi==2022.12.7
charset-normalizer==3.1.0
cmake==3.26.1
diffusers==0.14.0
einops==0.6.0
filelock==3.11.0
huggingface-hub==0.13.3
idna==3.4
imageio-ffmpeg==0.4.8
importlib-metadata==6.1.0
Jinja2==3.1.2
lit==16.0.0
MarkupSafe==2.1.2
mpmath==1.3.0
networkx==3.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
opencv-python-headless==4.7.0.72
packaging==23.0
Pillow==9.5.0
psutil==5.9.4
PyYAML==6.0
regex==2023.3.23
requests==2.28.2
sympy==1.11.1
tokenizers==0.13.2
torch==2.0.0
torchvision==0.15.1+cu117
tqdm==4.65.0
transformers==4.28.1
triton==2.0.0
typing_extensions==4.5.0
urllib3==1.26.15
zipp==3.15.0
```
My env building script (2023.4.18):
```shell
#!/bin/bash
set -e

CONDA_P=${1-"$HOME/miniconda3"}
CONDA_BIN=$CONDA_P/bin
ENV=ldm
if [ ! -d $CONDA_P/envs/$ENV ]; then
    $CONDA_BIN/conda create --name $ENV python=3.10 -y
fi
ENV_BIN=$CONDA_P/envs/$ENV/bin

$ENV_BIN/pip install --upgrade diffusers[torch]
$ENV_BIN/pip install torchvision --index-url https://download.pytorch.org/whl/cu117

echo misc
conda install -n $ENV click scipy tqdm ninja matplotlib imageio pandas -y
for pkg in \
    imageio-ffmpeg opencv-python-headless omegaconf einops transformers
do
    $ENV_BIN/pip install $pkg
done
```
I guess this may be a matter of the package version. Can you share your environment configuration?

**Comment by samggggflynn** [comment]
I met same issue, solved by just delete `models/unet_dual_encoder.py` , line 16 , " from diffusers.models import BasicTransformerBlock" . Because it used in code.

**Comment by iTomxy** [comment]
Nice~
By the way, I solve it, too. By inspecting [huggingface/diffusers/src/diffusers/models/attention.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention.py#L177), I change [this importing](https://github.com/johannakarras/DreamPose/blob/main/models/unet_dual_encoder.py#L16) to:
```python
from diffusers.models.attention import BasicTransformerBlock
```
