### ISSUE TITLE
how to download the specific revision of Stable Diffusion weights?

### ISSUE THREAD

**Issue by iTomxy** [johannakarras/DreamPose#35]
I got the following error when I run [finetune-unet.py](https://github.com/johannakarras/DreamPose/blob/main/finetune-unet.py):
```
Traceback (most recent call last):
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 356, in load_config
    config_file = hf_hub_download(
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1227, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/itom/codes/tmp.DreamPose/finetune-unet.py", line 456, in <module>
    main(args)
  File "/home/itom/codes/tmp.DreamPose/finetune-unet.py", line 105, in main
    unet = get_unet(args.pretrained_model_name_or_path, args.revision, resolution=args.resolution)
  File "/home/itom/codes/tmp.DreamPose/models/unet_dual_encoder.py", line 19, in get_unet
    unet = UNet2DConditionModel.from_pretrained(
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 494, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 383, in load_config
    raise EnvironmentError(
OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named config.json.
Traceback (most recent call last):
  File "/home/itom/miniconda3/envs/ldm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 915, in launch_command
    simple_launcher(args)
  File "/home/itom/miniconda3/envs/ldm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 578, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/itom/miniconda3/envs/ldm/bin/python', 'finetune-unet.py', '--pretrained_model_name_or_path', 'CompVis/stable-diffusion-v1-4', '--instance_data_dir', 'inputs/fine-tune/iPER/sample-val-first100/001_9_1', '--output_dir=checkpoints/001_9_1', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-5', '--num_train_epochs=500', '--dropout_rate=0.0', '--custom_chkpt=checkpoints/original/unet_epoch_20.pth', '--revision', 'ebb811dd71cdc38a204ecbdd6ac5d580f529fd8c']' returned non-zero exit status 1.
```
Seems that my server can't download the pretrained weights properly. I want to download the Stable Diffusion v1.4 manually.

But I can't find the revision specified at [README/Finetune on Sample](https://github.com/johannakarras/DreamPose#finetune-on-sample), i.e. `ebb811dd71cdc38a204ecbdd6ac5d580f529fd8c`. As said in [1,2], I guess it might be a commit id. But I can't find it in the commit history of [CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4).

So how the download the pretrained Stable Diffusion weight of that revision? Or can I just use the newest one?

---

1. [Huggingface models: how to store a different version of a model](https://stackoverflow.com/questions/73788355/huggingface-models-how-to-store-a-different-version-of-a-model)
2. [revision](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.from_pretrained.revision)

**Comment by ghost** [comment]
I'm having the same issue, pls have you solved it now

**Comment by zeezou-isee** [comment]
I meet the same question too, i wonder whether you have solved or not. I appreciate that if i got your help!

**Comment by nlilin** [comment]
> whether

Download Huggingface with training parameters to your local and make sure your region can do it.

**Comment by ghost** [comment]
> I meet the same question too, i wonder whether you have solved or not. I appreciate that if i got your help!

Download Huggingface with training parameters to your local.

**Comment by zeezou-isee** [comment]
> > I meet the same question too, i wonder whether you have solved or not. I appreciate that if i got your help!
> 
> Download Huggingface with training parameters to your local.

Thanks  for mentioning me for that ,now I can reproduce this project!
