### ISSUE TITLE
dict key error in demo

### ISSUE THREAD

**Issue by DmitriyPin** [johannakarras/DreamPose#49]
Hello,
When I am running demo, I am getting the following dictionary key error. I am using PyTorch 2.0.1 and cuda 11.7. Is that specific version of PyTorch that I should use? Any ideas how I can resolve this?
Thank you

```
Traceback (most recent call last):
  File "test.py", line 87, in <module>
    pipe.vae.load_state_dict(new_state_dict)
  File "C:\Users\best4\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.value.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.proj_attn.bias".
```

**Comment by VoHoangAnh** [comment]
have you fixed it yet?
I have the same problem.

**Comment by DmitriyPin** [comment]
no , I do not have a fix for this

**Comment by hughkhu** [comment]
I have the same problem.

**Comment by VoHoangAnh** [comment]
I replaced keywords and it worked.

**Comment by LaiaTarres** [comment]
Same! I have replaced it like this and now it doesn't give me this error anymore:

```
        name = name.replace('query.', 'to_q.')
        name = name.replace('key.', 'to_k.')
        name = name.replace('value.', 'to_v.')
        name = name.replace('proj_attn.', 'to_out.')
        name = name.replace('.mid_block.attentions.0.to_out.', '.mid_block.attentions.0.to_out.0.')
```

**Comment by TrainColab** [comment]
@LaiaTarres  hi Laia can u plz help me to find, where should replace this keywords (file name + ligne) . and thank you so much

**Comment by wasa4587** [comment]
> Same! I have replaced it like this and now it doesn't give me this error anymore:
> 
> ```
>         name = name.replace('query.', 'to_q.')
>         name = name.replace('key.', 'to_k.')
>         name = name.replace('value.', 'to_v.')
>         name = name.replace('proj_attn.', 'to_out.')
>         name = name.replace('.mid_block.attentions.0.to_out.', '.mid_block.attentions.0.to_out.0.')
> ```

commit 978b1aef8c11afefaf9cfb94cd710351cc1229f3
win10 wsl 

uname -r 
5.15.133.1-microsoft-standard-WSL2

I added those on line 87

if args.custom_vae is not None:
    vae_chkpt = args.custom_vae
    print("Loading custom vae checkpoint from ", vae_chkpt, '...')
    vae_state_dict = torch.load(vae_chkpt)
    new_state_dict = OrderedDict()
    for k, v in vae_state_dict.items():
        name = k.replace('module.', '')  #name = k[7:] if k[:7] == 'module' else k 
        new_state_dict[name] = v
        name = name.replace('query.', 'to_q.')
        name = name.replace('key.', 'to_k.')
        name = name.replace('value.', 'to_v.')
        name = name.replace('proj_attn.', 'to_out.')
        name = name.replace('.mid_block.attentions.0.to_out.', '.mid_block.attentions.0.to_out.0.')
    pipe.vae.load_state_dict(new_state_dict)
    pipe.vae = pipe.vae.cuda()
    
    
Still having the same issue


Loading custom vae checkpoint from  /mnt/d/DreamPose/demo/custom-chkpts/vae_1499.pth ...
Traceback (most recent call last):
  File "/home/wasa/videos/DreamPose/test.py", line 92, in <module>
    pipe.vae.load_state_dict(new_state_dict)
  File "/home/wasa/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.value.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.proj_attn.bias".

**Comment by xavier111222** [comment]
@LaiaTarres  Can you send any code that needs to be changed or replaced? I would love to be able to test it because it really amazes me zonqio@outlook.com Thank you

**Comment by SaharaSheik** [comment]
I fixed this by modifying the [line ](https://github.com/johannakarras/DreamPose/blob/5bf30b7df70cf6f2e0bb25556c6ff2cbf0f2b1bf/test.py#L53)(this is a common issues so all you need to do is toc change the state dict names such that they match your expected state:

```python
    for k, v in vae_state_dict.items():
        name1 = k.replace('module.', '')  #name = k[7:] if k[:7] == 'module' else k
        name2 = name1.replace('query', 'to_q')  #name = k[7:] if k[:7] == 'module' else k
        name3 = name2.replace('key', 'to_k')
        name4 = name3.replace('value', 'to_v')
        name = name4.replace('proj_attn', 'to_out.0')
        new_state_dict[name] = v
    pipe.vae.load_state_dict(new_state_dict)
    pipe.vae = pipe.vae.cuda()

```
