### ISSUE TITLE
Logging_dir

### ISSUE THREAD

**Issue by Nwosu-Ihueze** [johannakarras/DreamPose#68]
I'm trying to finetune with my own data and I ran into this error

```
Traceback (most recent call last):
  File "/content/drive/MyDrive/DreamPose/finetune-unet.py", line 453, in <module>
    main(args)
  File "/content/drive/MyDrive/DreamPose/finetune-unet.py", line 54, in main
    accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'logging_dir'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'finetune-unet.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=demo/sample/train', '--output_dir=demo/custom-chkpts', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-5', '--num_train_epochs=500', '--dropout_rate=0.0', '--custom_chkpt=checkpoints/unet_epoch_20.pth', '--revision', 'ebb811dd71cdc38a204ecbdd6ac5d580f529fd8c']' returned non-zero exit status 1.
```

**Comment by Nwosu-Ihueze** [comment]
The solution is to change `logging_dir=logging_dir` to `project_dir=logging_dir` for both finetune_vae and finetune_unet
